image: debian:latest

before_script:
  - apt-get update -qq
  - apt-get install -qq -y --no-install-recommends
            git gcc make autoconf automake libtool gcovr
  - ./autogen

unit-tests:
  stage: test
  script:
    - ./configure --enable-sanitize
    - make check

coverage:
  stage: test
  script:
    - ./configure --disable-static
    - make check CFLAGS="--coverage -O0 -ggdb" LDFLAGS="--coverage -O0 -ggdb"
    - gcovr -s -e test/
